version: "3"
services:
  app:
    image: nodeimage
    container_name: nodeserver
    build: ./
    restart: always
    ports:
    - "80:80"
    environment:
      - HOST=54.166.245.125
      - PORT=80
